version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: product-catalog-postgres
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catalog_user -d catalog_db" ]
      interval: 10s
      timeout: 5s
      retries: 5



networks:
  catalog-network:
    driver: bridge
